name: Update Absensi

on:
  schedule:
    - cron: "0 0 * * *" # Menjalankan setiap hari pukul 00:00 UTC
  workflow_dispatch: # Memungkinkan workflow dijalankan secara manual

jobs:
  run-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Panggil Edge Function Supabase
        run: |
          curl -X POST "https://tlwejtywxlznzjfacxg.supabase.co/functions/v1/auto-presence" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_KEY }}"
